package com.creasypita.drools.rules;

import com.creasypita.drools.model.Applicant;

global com.creasypita.drools.model.SuggestedRole suggestedRole;

dialect  "mvel"

rule "Suggest Manager Role"
    when
        Applicant(experienceInYears > 10)
        Applicant(currentSalary > 1000000 && currentSalary <= 2500000)
    then
        suggestedRole.setRole("Manager");
end

rule "Suggest Senior developer Role"
    when
        Applicant(experienceInYears > 5 && experienceInYears <= 10)
        Applicant(currentSalary > 500000 && currentSalary <= 1500000)
    then
        suggestedRole.setRole("Senior developer");
end

rule "Suggest Developer Role"
    when
        Applicant(experienceInYears > 0 && experienceInYears <= 5)
        Applicant(currentSalary > 200000 && currentSalary <= 1000000)
    then
        suggestedRole.setRole("Developer");
end

rule "Suggest assist Developer Role"
    when
        Applicant(experienceInYears > 0 && experienceInYears <= 1)
    then
        suggestedRole.setRole("assist Developer");
end

rule "Other Role"
    when
        eval(checkIsTheRuleInvokeWhenNotFire(null))
    then
        suggestedRole.setRole("no Manager");
end

function Boolean FireSuggestManagerRole(){
//    logger.info("invoking checkIsInvokeWhenNotFire");
    System.out.println("invoking FireSuggestManagerRole");
    return true;
}

function Boolean checkIsTheRuleInvokeWhenNotFire(String a){
//    logger.info("invoking checkIsInvokeWhenNotFire");
    System.out.println("invoking checkIsTheRuleInvokeWhenNotFire");
    return true;
//    return a.length()>10;
}
